version: '3.9'

services:
  velesio-aiserver:
    image: teocholakov/velesio-aiserver
    container_name: velesio-aiserver
    ports:
      # - "6969:6969" # for nginx reverse proxy
      - "7860:7860"
      - "1337:1337" # -> 1338 internal
      - "1339:1339" # -> 1340 internal
      - "1341:1341" # -> 1342 internal
      - "1343:1343" # -> 1344 internal
      - "1345:1345" # -> 1346 internal
      - "3000:3000"
    volumes:
      - ./models/stable-diffusion:/models/stable-diffusion
      - ./models/llm:/models/llm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # 172.18.0.1 
      - ALLOWLIST_FRONTEND=0.0.0.0/0
      - ALLOWLIST_LLM=0.0.0.0/0
      - ALLOWLIST_SD=0.0.0.0/0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped