version: '3.9'

services:
  velesio-aiserver:
    build:
      context: ..
      dockerfile: shared/Dockerfile.runpod
    image: teocholakov/velesio-aiserver
    container_name: velesio-aiserver
    ports:
      - "6969:6969"
    volumes:
      - ./models/stable-diffusion:/models/stable-diffusion
      - ./models/llm:/models/llm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - ALLOWLIST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped